project_id = "mfickczwrzsarfkoosoh"

[functions.planner-chat]
verify_jwt = false

[functions.meta-app-config]
verify_jwt = false

[functions.meta-oauth-callback]
verify_jwt = false

[functions.fetch-meta-adaccounts]
verify_jwt = false

[functions.fetch-meta-insights]
verify_jwt = false
